package bean;
// Generated 13/10/2025 22:07:14 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Phspusuarios generated by hbm2java
 */
@Entity
@Table(name="phspusuarios"
    ,catalog="db_pedro_pires"
)
public class Phspusuarios  implements java.io.Serializable {


     private int phspIdUsuarios;
     private String phspNome;
     private String phspApelido;
     private String phspCpf;
     private Date phspDataNascimento;
     private String phspSenha;
     private int phspNivel;
     private String phspAtivo;

    public Phspusuarios() {
    }

	
    public Phspusuarios(int phspIdUsuarios, String phspNome, String phspApelido, String phspCpf, Date phspDataNascimento, String phspSenha, int phspNivel, String phspAtivo) {
        this.phspIdUsuarios = phspIdUsuarios;
        this.phspNome = phspNome;
        this.phspApelido = phspApelido;
        this.phspCpf = phspCpf;
        this.phspDataNascimento = phspDataNascimento;
        this.phspSenha = phspSenha;
        this.phspNivel = phspNivel;
        this.phspAtivo = phspAtivo;
    }
    public Phspusuarios(int phspIdUsuarios, String phspNome, String phspApelido, String phspCpf, Date phspDataNascimento, String phspSenha, int phspNivel, String phspAtivo, Set phspvendases) {
       this.phspIdUsuarios = phspIdUsuarios;
       this.phspNome = phspNome;
       this.phspApelido = phspApelido;
       this.phspCpf = phspCpf;
       this.phspDataNascimento = phspDataNascimento;
       this.phspSenha = phspSenha;
       this.phspNivel = phspNivel;
       this.phspAtivo = phspAtivo;
    }
   
     @Id 

    
    @Column(name="phsp_idUsuarios", unique=true, nullable=false)
    public int getPhspIdUsuarios() {
        return this.phspIdUsuarios;
    }
    
    public void setPhspIdUsuarios(int phspIdUsuarios) {
        this.phspIdUsuarios = phspIdUsuarios;
    }

    
    @Column(name="phsp_nome", nullable=false, length=50)
    public String getPhspNome() {
        return this.phspNome;
    }
    
    public void setPhspNome(String phspNome) {
        this.phspNome = phspNome;
    }

    
    @Column(name="phsp_apelido", nullable=false, length=25)
    public String getPhspApelido() {
        return this.phspApelido;
    }
    
    public void setPhspApelido(String phspApelido) {
        this.phspApelido = phspApelido;
    }

    
    @Column(name="phsp_cpf", nullable=false, length=14)
    public String getPhspCpf() {
        return this.phspCpf;
    }
    
    public void setPhspCpf(String phspCpf) {
        this.phspCpf = phspCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="phsp_dataNascimento", length=10)
    public Date getPhspDataNascimento() {
        return this.phspDataNascimento;
    }
    
    public void setPhspDataNascimento(Date phspDataNascimento) {
        this.phspDataNascimento = phspDataNascimento;
    }

    
    @Column(name="phsp_senha", nullable=false, length=20)
    public String getPhspSenha() {
        return this.phspSenha;
    }
    
    public void setPhspSenha(String phspSenha) {
        this.phspSenha = phspSenha;
    }

    
    @Column(name="phsp_nivel", nullable=false)
    public int getPhspNivel() {
        return this.phspNivel;
    }
    
    public void setPhspNivel(int phspNivel) {
        this.phspNivel = phspNivel;
    }

    
    @Column(name="phsp_ativo", nullable=false, length=1)
    public String getPhspAtivo() {
        return this.phspAtivo;
    }
    
    public void setPhspAtivo(String phspAtivo) {
        this.phspAtivo = phspAtivo;
    }




}


