package bean;
// Generated 13/10/2025 22:07:14 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Phspfuncionarios generated by hbm2java
 */
@Entity
@Table(name="phspfuncionarios"
    ,catalog="db_pedro_pires"
)
public class Phspfuncionarios  implements java.io.Serializable {


     private int phspIdFuncionario;
     private String phspNome;
     private String phspCpf;
     private String phspEmail;
     private String phspTelefone;
     private String phspCargo;
     private Date phspDataAdmissao;

    public Phspfuncionarios() {
    }

    public Phspfuncionarios(int phspIdFuncionario, String phspNome, String phspCpf, String phspEmail, String phspTelefone, String phspCargo, Date phspDataAdmissao) {
       this.phspIdFuncionario = phspIdFuncionario;
       this.phspNome = phspNome;
       this.phspCpf = phspCpf;
       this.phspEmail = phspEmail;
       this.phspTelefone = phspTelefone;
       this.phspCargo = phspCargo;
       this.phspDataAdmissao = phspDataAdmissao;
    }
   
     @Id 

    
    @Column(name="phsp_idFuncionario", unique=true, nullable=false)
    public int getPhspIdFuncionario() {
        return this.phspIdFuncionario;
    }
    
    public void setPhspIdFuncionario(int phspIdFuncionario) {
        this.phspIdFuncionario = phspIdFuncionario;
    }

    
    @Column(name="phsp_nome", nullable=false, length=100)
    public String getPhspNome() {
        return this.phspNome;
    }
    
    public void setPhspNome(String phspNome) {
        this.phspNome = phspNome;
    }

    
    @Column(name="phsp_CPF", nullable=false, length=14)
    public String getPhspCpf() {
        return this.phspCpf;
    }
    
    public void setPhspCpf(String phspCpf) {
        this.phspCpf = phspCpf;
    }

    
    @Column(name="phsp_email", nullable=false, length=80)
    public String getPhspEmail() {
        return this.phspEmail;
    }
    
    public void setPhspEmail(String phspEmail) {
        this.phspEmail = phspEmail;
    }

    
    @Column(name="phsp_telefone", nullable=false, length=15)
    public String getPhspTelefone() {
        return this.phspTelefone;
    }
    
    public void setPhspTelefone(String phspTelefone) {
        this.phspTelefone = phspTelefone;
    }

    
    @Column(name="phsp_Cargo", nullable=false, length=50)
    public String getPhspCargo() {
        return this.phspCargo;
    }
    
    public void setPhspCargo(String phspCargo) {
        this.phspCargo = phspCargo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="phsp_dataAdmissao", length=10)
    public Date getPhspDataAdmissao() {
        return this.phspDataAdmissao;
    }
    
    public void setPhspDataAdmissao(Date phspDataAdmissao) {
        this.phspDataAdmissao = phspDataAdmissao;
    }




}


