package bean;
// Generated 13/10/2025 22:07:14 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Phspvendas generated by hbm2java
 */
@Entity
@Table(name="phspvendas"
    ,catalog="db_pedro_pires"
)
public class Phspvendas  implements java.io.Serializable {


     private int phspIdVendas;
     private Phspclientes phspclientes;
     private Phspusuarios phspusuarios;
     private Date phspDataVenda;
     private Double phspTotal;
     private String phspFormaPagamento;
     private String phspDesconto;

    public Phspvendas() {
    }

	
    public Phspvendas(int phspIdVendas, Phspclientes phspclientes, Phspusuarios phspusuarios, Date phspDataVenda, Double phspTotal, String phspFormaPagamento, String phspDesconto) {
        this.phspIdVendas = phspIdVendas;
        this.phspclientes = phspclientes;
        this.phspusuarios = phspusuarios;
        this.phspDataVenda = phspDataVenda;
        this.phspTotal = phspTotal;
        this.phspFormaPagamento = phspFormaPagamento;
        this.phspDesconto = phspDesconto;
    }
    public Phspvendas(int phspIdVendas, Phspclientes phspclientes, Phspusuarios phspusuarios, Date phspDataVenda, Double phspTotal, String phspFormaPagamento, String phspDesconto, Set phspvendasprodutoses) {
       this.phspIdVendas = phspIdVendas;
       this.phspclientes = phspclientes;
       this.phspusuarios = phspusuarios;
       this.phspDataVenda = phspDataVenda;
       this.phspTotal = phspTotal;
       this.phspFormaPagamento = phspFormaPagamento;
       this.phspDesconto = phspDesconto;
    }
   
     @Id 

    
    @Column(name="phsp_idVendas", unique=true, nullable=false)
    public int getPhspIdVendas() {
        return this.phspIdVendas;
    }
    
    public void setPhspIdVendas(int phspIdVendas) {
        this.phspIdVendas = phspIdVendas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="phsp_cliente", nullable=false)
    public Phspclientes getPhspclientes() {
        return this.phspclientes;
    }
    
    public void setPhspclientes(Phspclientes phspclientes) {
        this.phspclientes = phspclientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="phsp_usuario", nullable=false)
    public Phspusuarios getPhspusuarios() {
        return this.phspusuarios;
    }
    
    public void setPhspusuarios(Phspusuarios phspusuarios) {
        this.phspusuarios = phspusuarios;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="phsp_dataVenda", length=10)
    public Date getPhspDataVenda() {
        return this.phspDataVenda;
    }
    
    public void setPhspDataVenda(Date phspDataVenda) {
        this.phspDataVenda = phspDataVenda;
    }

    
    @Column(name="phsp_total", nullable=false, precision=10)
    public Double getPhspTotal() {
        return this.phspTotal;
    }
    
    public void setPhspTotal(Double phspTotal) {
        this.phspTotal = phspTotal;
    }

    
    @Column(name="phsp_forma_pagamento", nullable=false, length=50)
    public String getPhspFormaPagamento() {
        return this.phspFormaPagamento;
    }
    
    public void setPhspFormaPagamento(String phspFormaPagamento) {
        this.phspFormaPagamento = phspFormaPagamento;
    }

    
    @Column(name="phsp_desconto", nullable=false, length=10)
    public String getPhspDesconto() {
        return this.phspDesconto;
    }
    
    public void setPhspDesconto(String phspDesconto) {
        this.phspDesconto = phspDesconto;
    }



}


