package bean;
// Generated 13/10/2025 22:07:14 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Phspvendasprodutos generated by hbm2java
 */
@Entity
@Table(name="phspvendasprodutos"
    ,catalog="db_pedro_pires"
)
public class Phspvendasprodutos  implements java.io.Serializable {


     private int phspIdVendasProdutos;
     private Phspprodutos phspprodutos;
     private Phspvendas phspvendas;
     private int phspQuantidade;
     private Double phspValorUnitario;

    public Phspvendasprodutos() {
    }

    public Phspvendasprodutos(int phspIdVendasProdutos, Phspprodutos phspprodutos, Phspvendas phspvendas, int phspQuantidade, Double phspValorUnitario) {
       this.phspIdVendasProdutos = phspIdVendasProdutos;
       this.phspprodutos = phspprodutos;
       this.phspvendas = phspvendas;
       this.phspQuantidade = phspQuantidade;
       this.phspValorUnitario = phspValorUnitario;
    }
   
     @Id 

    
    @Column(name="phsp_idVendasProdutos", unique=true, nullable=false)
    public int getPhspIdVendasProdutos() {
        return this.phspIdVendasProdutos;
    }
    
    public void setPhspIdVendasProdutos(int phspIdVendasProdutos) {
        this.phspIdVendasProdutos = phspIdVendasProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="phsp_produto", nullable=false)
    public Phspprodutos getPhspprodutos() {
        return this.phspprodutos;
    }
    
    public void setPhspprodutos(Phspprodutos phspprodutos) {
        this.phspprodutos = phspprodutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="phsp_venda", nullable=false)
    public Phspvendas getPhspvendas() {
        return this.phspvendas;
    }
    
    public void setPhspvendas(Phspvendas phspvendas) {
        this.phspvendas = phspvendas;
    }

    
    @Column(name="phsp_quantidade", nullable=false)
    public int getPhspQuantidade() {
        return this.phspQuantidade;
    }
    
    public void setPhspQuantidade(int phspQuantidade) {
        this.phspQuantidade = phspQuantidade;
    }

    
    @Column(name="phsp_valor_unitario", nullable=false, precision=10)
    public Double getPhspValorUnitario() {
        return this.phspValorUnitario;
    }
    
    public void setPhspValorUnitario(Double phspValorUnitario) {
        this.phspValorUnitario = phspValorUnitario;
    }




}


