package bean;
// Generated 13/10/2025 22:07:14 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Phspclientes generated by hbm2java
 */
@Entity
@Table(name="phspclientes"
    ,catalog="db_pedro_pires"
)
public class Phspclientes  implements java.io.Serializable {


     private int phspIdClientes;
     private String phspNome;
     private String phspCpf;
     private String phspEmail;
     private String phspTelefone;
     private String phspEndereco;
     private String phspCidade;
     private String phspEstado;
     private String phspCep;
     private Date phspDataNascimento;
     private String phspGenero;
     private String phspSenha;
     private Date phspDataCadastro;
     private String phspStatus;
     private String phspPais;

    public Phspclientes() {
    }

	
    public Phspclientes(int phspIdClientes, String phspNome, String phspCpf, String phspEmail, String phspTelefone, String phspEndereco, String phspCidade, String phspEstado, String phspCep, Date phspDataNascimento, String phspSenha, Date phspDataCadastro, String phspStatus, String phspPais) {
        this.phspIdClientes = phspIdClientes;
        this.phspNome = phspNome;
        this.phspCpf = phspCpf;
        this.phspEmail = phspEmail;
        this.phspTelefone = phspTelefone;
        this.phspEndereco = phspEndereco;
        this.phspCidade = phspCidade;
        this.phspEstado = phspEstado;
        this.phspCep = phspCep;
        this.phspDataNascimento = phspDataNascimento;
        this.phspSenha = phspSenha;
        this.phspDataCadastro = phspDataCadastro;
        this.phspStatus = phspStatus;
        this.phspPais = phspPais;
    }
    public Phspclientes(int phspIdClientes, String phspNome, String phspCpf, String phspEmail, String phspTelefone, String phspEndereco, String phspCidade, String phspEstado, String phspCep, Date phspDataNascimento, String phspGenero, String phspSenha, Date phspDataCadastro, String phspStatus, String phspPais, Set phspvendases) {
       this.phspIdClientes = phspIdClientes;
       this.phspNome = phspNome;
       this.phspCpf = phspCpf;
       this.phspEmail = phspEmail;
       this.phspTelefone = phspTelefone;
       this.phspEndereco = phspEndereco;
       this.phspCidade = phspCidade;
       this.phspEstado = phspEstado;
       this.phspCep = phspCep;
       this.phspDataNascimento = phspDataNascimento;
       this.phspGenero = phspGenero;
       this.phspSenha = phspSenha;
       this.phspDataCadastro = phspDataCadastro;
       this.phspStatus = phspStatus;
       this.phspPais = phspPais;
        }
   
     @Id 

    
    @Column(name="phsp_idClientes", unique=true, nullable=false)
    public int getPhspIdClientes() {
        return this.phspIdClientes;
    }
    
    public void setPhspIdClientes(int phspIdClientes) {
        this.phspIdClientes = phspIdClientes;
    }

    
    @Column(name="phsp_nome", nullable=false, length=100)
    public String getPhspNome() {
        return this.phspNome;
    }
    
    public void setPhspNome(String phspNome) {
        this.phspNome = phspNome;
    }

    
    @Column(name="phsp_cpf", nullable=false, length=14)
    public String getPhspCpf() {
        return this.phspCpf;
    }
    
    public void setPhspCpf(String phspCpf) {
        this.phspCpf = phspCpf;
    }

    
    @Column(name="phsp_email", nullable=false, length=80)
    public String getPhspEmail() {
        return this.phspEmail;
    }
    
    public void setPhspEmail(String phspEmail) {
        this.phspEmail = phspEmail;
    }

    
    @Column(name="phsp_telefone", nullable=false, length=15)
    public String getPhspTelefone() {
        return this.phspTelefone;
    }
    
    public void setPhspTelefone(String phspTelefone) {
        this.phspTelefone = phspTelefone;
    }

    
    @Column(name="phsp_endereco", nullable=false, length=200)
    public String getPhspEndereco() {
        return this.phspEndereco;
    }
    
    public void setPhspEndereco(String phspEndereco) {
        this.phspEndereco = phspEndereco;
    }

    
    @Column(name="phsp_cidade", nullable=false, length=100)
    public String getPhspCidade() {
        return this.phspCidade;
    }
    
    public void setPhspCidade(String phspCidade) {
        this.phspCidade = phspCidade;
    }

    
    @Column(name="phsp_estado", nullable=false, length=50)
    public String getPhspEstado() {
        return this.phspEstado;
    }
    
    public void setPhspEstado(String phspEstado) {
        this.phspEstado = phspEstado;
    }

    
    @Column(name="phsp_cep", nullable=false, length=10)
    public String getPhspCep() {
        return this.phspCep;
    }
    
    public void setPhspCep(String phspCep) {
        this.phspCep = phspCep;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="phsp_data_nascimento", length=10)
    public Date getPhspDataNascimento() {
        return this.phspDataNascimento;
    }
    
    public void setPhspDataNascimento(Date phspDataNascimento) {
        this.phspDataNascimento = phspDataNascimento;
    }

    
    @Column(name="phsp_genero", length=20)
    public String getPhspGenero() {
        return this.phspGenero;
    }
    
    public void setPhspGenero(String phspGenero) {
        this.phspGenero = phspGenero;
    }

    
    @Column(name="phsp_senha", nullable=false)
    public String getPhspSenha() {
        return this.phspSenha;
    }
    
    public void setPhspSenha(String phspSenha) {
        this.phspSenha = phspSenha;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="phsp_data_cadastro", length=10)
    public Date getPhspDataCadastro() {
        return this.phspDataCadastro;
    }
    
    public void setPhspDataCadastro(Date phspDataCadastro) {
        this.phspDataCadastro = phspDataCadastro;
    }

    
    @Column(name="phsp_status", nullable=false, length=20)
    public String getPhspStatus() {
        return this.phspStatus;
    }
    
    public void setPhspStatus(String phspStatus) {
        this.phspStatus = phspStatus;
    }

    
    @Column(name="phsp_pais", nullable=false, length=50)
    public String getPhspPais() {
        return this.phspPais;
    }
    
    public void setPhspPais(String phspPais) {
        this.phspPais = phspPais;
    }



}


