package bean;
// Generated 13/10/2025 22:07:14 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Phspprodutos generated by hbm2java
 */
@Entity
@Table(name="phspprodutos"
    ,catalog="db_pedro_pires"
)
public class Phspprodutos  implements java.io.Serializable {


     private int phspIdProdutos;
     private String phspNome;
     private String phspCategoria;
     private String phspPlataforma;
     private Double  phspPreco;
     private Date phspLancamento;
     private String phspDescricao;

    public Phspprodutos() {
    }

	
    public Phspprodutos(int phspIdProdutos, String phspNome, String phspCategoria, String phspPlataforma, Double  phspPreco, Date phspLancamento, String phspDescricao) {
        this.phspIdProdutos = phspIdProdutos;
        this.phspNome = phspNome;
        this.phspCategoria = phspCategoria;
        this.phspPlataforma = phspPlataforma;
        this.phspPreco = phspPreco;
        this.phspLancamento = phspLancamento;
        this.phspDescricao = phspDescricao;
    }
    public Phspprodutos(int phspIdProdutos, String phspNome, String phspCategoria, String phspPlataforma, Double  phspPreco, Date phspLancamento, String phspDescricao, Set phspvendasprodutoses) {
       this.phspIdProdutos = phspIdProdutos;
       this.phspNome = phspNome;
       this.phspCategoria = phspCategoria;
       this.phspPlataforma = phspPlataforma;
       this.phspPreco = phspPreco;
       this.phspLancamento = phspLancamento;
       this.phspDescricao = phspDescricao;
    }
   
     @Id 

    
    @Column(name="phsp_idProdutos", unique=true, nullable=false)
    public int getPhspIdProdutos() {
        return this.phspIdProdutos;
    }
    
    public void setPhspIdProdutos(int phspIdProdutos) {
        this.phspIdProdutos = phspIdProdutos;
    }

    
    @Column(name="phsp_nome", nullable=false, length=100)
    public String getPhspNome() {
        return this.phspNome;
    }
    
    public void setPhspNome(String phspNome) {
        this.phspNome = phspNome;
    }

    
    @Column(name="phsp_categoria", nullable=false, length=50)
    public String getPhspCategoria() {
        return this.phspCategoria;
    }
    
    public void setPhspCategoria(String phspCategoria) {
        this.phspCategoria = phspCategoria;
    }

    
    @Column(name="phsp_plataforma", nullable=false, length=50)
    public String getPhspPlataforma() {
        return this.phspPlataforma;
    }
    
    public void setPhspPlataforma(String phspPlataforma) {
        this.phspPlataforma = phspPlataforma;
    }

    
    @Column(name="phsp_preco", nullable=false, precision=10)
    public Double  getPhspPreco() {
        return this.phspPreco;
    }
    
    public void setPhspPreco(Double  phspPreco) {
        this.phspPreco = phspPreco;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="phsp_lancamento", length=10)
    public Date getPhspLancamento() {
        return this.phspLancamento;
    }
    
    public void setPhspLancamento(Date phspLancamento) {
        this.phspLancamento = phspLancamento;
    }

    
    @Column(name="phsp_descricao", nullable=false, length=150)
    public String getPhspDescricao() {
        return this.phspDescricao;
    }
    
    public void setPhspDescricao(String phspDescricao) {
        this.phspDescricao = phspDescricao;
    }





}


